name: Release

on:
  release:
    types: published

jobs:
  plugin_dst:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      #    Needed if the plugin is using Transifex, to have the lrelease command
      #    - name: Install Qt lrelease
      #      run: sudo apt-get install qt5-default qttools5-dev-tools

      # sets up an "environment" tag for Sentry
      - name: Set up a Sentry environment
        run: |
          sed -i "s/PLUGIN_ENVIRONMENT='local'/PLUGIN_ENVIRONMENT='production'/" Unfolded/sentry.py

      - name: Install qgis-plugin-ci
        run: pip3 install qgis-plugin-ci

      # the current OSGEO_USERNAME_FSQ and OSGEO_PASSWORD_FSQ are tied to:
      # user: https://plugins.qgis.org/plugins/user/foursquare
      # email: dokanovic@foursquare.com
      #
      # When osgeo upload is wanted: --osgeo-username usrname --osgeo-password ${{ secrets.OSGEO_PASSWORD_FSQ }}
      # When Transifex is wanted: --transifex-token ${{ secrets.TRANSIFEX_TOKEN }}
      - name: Deploy plugin
        run: qgis-plugin-ci release ${GITHUB_REF/refs\/tags\//} --github-token ${{ secrets.GITHUB_TOKEN }} --disable-submodule-update --osgeo-username ${{ secrets.OSGEO_USERNAME_FSQ }} --osgeo-password ${{ secrets.OSGEO_PASSWORD_FSQ }} --allow-uncommitted-changes
